// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnetw-qVBdieCPKqxh7hNy8NXEU8nP6Hk',
    appId: '1:313944664215:web:224a44e1bea6d5e2c1e1d2',
    messagingSenderId: '313944664215',
    projectId: 'careerpath-4d6ff',
    authDomain: 'careerpath-4d6ff.firebaseapp.com',
    databaseURL: 'https://careerpath-4d6ff-default-rtdb.firebaseio.com',
    storageBucket: 'careerpath-4d6ff.firebasestorage.app',
    measurementId: 'G-JYCX5H3L7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBf-QaqGoEMdUB_rVH8kp-Eg75dNgIJxc',
    appId: '1:313944664215:android:4d508298b66c035ec1e1d2',
    messagingSenderId: '313944664215',
    projectId: 'careerpath-4d6ff',
    databaseURL: 'https://careerpath-4d6ff-default-rtdb.firebaseio.com',
    storageBucket: 'careerpath-4d6ff.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCZNeXwOgPp7Pu2BNCZalzYZsGZJz9O8s',
    appId: '1:313944664215:ios:cf6eb333e657f71ec1e1d2',
    messagingSenderId: '313944664215',
    projectId: 'careerpath-4d6ff',
    databaseURL: 'https://careerpath-4d6ff-default-rtdb.firebaseio.com',
    storageBucket: 'careerpath-4d6ff.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCZNeXwOgPp7Pu2BNCZalzYZsGZJz9O8s',
    appId: '1:313944664215:ios:cf6eb333e657f71ec1e1d2',
    messagingSenderId: '313944664215',
    projectId: 'careerpath-4d6ff',
    databaseURL: 'https://careerpath-4d6ff-default-rtdb.firebaseio.com',
    storageBucket: 'careerpath-4d6ff.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnetw-qVBdieCPKqxh7hNy8NXEU8nP6Hk',
    appId: '1:313944664215:web:51bfd24735a4f0d8c1e1d2',
    messagingSenderId: '313944664215',
    projectId: 'careerpath-4d6ff',
    authDomain: 'careerpath-4d6ff.firebaseapp.com',
    databaseURL: 'https://careerpath-4d6ff-default-rtdb.firebaseio.com',
    storageBucket: 'careerpath-4d6ff.firebasestorage.app',
    measurementId: 'G-SQBN4EMM3Y',
  );
}
