import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:myapp/firebase_options.dart';

Future<void> main() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  print("======================================");
  print("   CAREER PATH - STUDENT CAREERS");
  print("======================================");
  print("");

  final FirebaseFirestore firestore = FirebaseFirestore.instance;

  // ============================================================
  // DELETE ONLY OLD STUDENT CAREERS
  // IMPORTANT:
  // Graduate and Professional careers will NOT be deleted.
  // ============================================================

  print("Deleting old student careers...");

  final QuerySnapshot oldStudentCareers = await firestore
      .collection("careerBank")
      .where("role", isEqualTo: "student")
      .get();

  for (final doc in oldStudentCareers.docs) {
    await doc.reference.delete();
  }

  print("Deleted ${oldStudentCareers.docs.length} old student careers.");
  print("");

  // ============================================================
  // STUDENT / UNDERGRADUATE PATHS
  // 12 CATEGORIES × 10 FIELDS = 120 FIELDS
  // ============================================================

  final List<Map<String, dynamic>> careers = [

    // ==========================================================
    // 1. COMPUTER SCIENCE & IT - 10
    // ==========================================================

    {
      "careerName": "Computer Science",
      "category": "computer",
      "categoryName": "Computer Science & IT",
      "role": "student",
      "description": "Studies programming, algorithms, software development, databases and computer systems.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Computer Science.",
      "skills": ["Programming", "Problem Solving", "Logical Thinking", "Mathematics"],
      "scope": "Provides pathways into software development, data science, artificial intelligence, cybersecurity and other technology careers.",
      "salaryRange": "Depends on the career and specialization chosen after graduation.",
    },
    {
      "careerName": "Software Engineering",
      "category": "computer",
      "categoryName": "Computer Science & IT",
      "role": "student",
      "description": "Focuses on designing, developing, testing and maintaining reliable software systems.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Software Engineering.",
      "skills": ["Programming", "Software Development", "Problem Solving", "Algorithms"],
      "scope": "Provides opportunities in software houses, technology companies, startups, banks and remote organizations.",
      "salaryRange": "Depends on the career, specialization and experience after graduation.",
    },
    {
      "careerName": "Artificial Intelligence",
      "category": "computer",
      "categoryName": "Computer Science & IT",
      "role": "student",
      "description": "Studies artificial intelligence, machine learning, intelligent systems and data-driven technologies.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Artificial Intelligence.",
      "skills": ["Python", "Mathematics", "Machine Learning", "Problem Solving"],
      "scope": "Provides pathways into AI engineering, machine learning, data science, automation and intelligent systems.",
      "salaryRange": "Depends on specialization and career chosen after graduation.",
    },
    {
      "careerName": "Data Science",
      "category": "computer",
      "categoryName": "Computer Science & IT",
      "role": "student",
      "description": "Combines statistics, programming and data analysis to discover useful information from data.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Data Science.",
      "skills": ["Statistics", "Python", "Data Analysis", "Mathematics"],
      "scope": "Provides opportunities in technology, finance, healthcare, research and business organizations.",
      "salaryRange": "Depends on specialization and experience after graduation.",
    },
    {
      "careerName": "Cybersecurity",
      "category": "computer",
      "categoryName": "Computer Science & IT",
      "role": "student",
      "description": "Focuses on protecting computer systems, networks, applications and data from security threats.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Cybersecurity or Information Security.",
      "skills": ["Networking", "Security", "Problem Solving", "Computer Systems"],
      "scope": "Provides pathways into security operations, ethical security testing, network security and information protection.",
      "salaryRange": "Depends on specialization and experience after graduation.",
    },
    {
      "careerName": "Information Technology",
      "category": "computer",
      "categoryName": "Computer Science & IT",
      "role": "student",
      "description": "Focuses on using computer systems, networks, databases and technology to support organizations.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Information Technology.",
      "skills": ["Computer Systems", "Networking", "Databases", "Problem Solving"],
      "scope": "Provides opportunities in IT support, system administration, networking, cloud services and business technology.",
      "salaryRange": "Depends on specialization and experience after graduation.",
    },
    {
      "careerName": "Information Systems",
      "category": "computer",
      "categoryName": "Computer Science & IT",
      "role": "student",
      "description": "Combines technology and business to manage information systems used by organizations.",
      "education": "After Intermediate or equivalent, students can pursue a degree in Information Systems or a related computing field.",
      "skills": ["Technology", "Business Analysis", "Databases", "Problem Solving"],
      "scope": "Provides pathways into business systems, technology consulting, database management and IT management.",
      "salaryRange": "Depends on specialization and experience after graduation.",
    },
    {
      "careerName": "Web Development",
      "category": "computer",
      "categoryName": "Computer Science & IT",
      "role": "student",
      "description": "Focuses on developing websites and web applications using modern web technologies.",
      "education": "Students can pursue a computing degree and develop web development skills through academic and practical learning.",
      "skills": ["HTML", "CSS", "JavaScript", "Programming"],
      "scope": "Provides pathways into frontend development, backend development, full-stack development and web application careers.",
      "salaryRange": "Depends on specialization, skills and experience after graduation.",
    },
    {
      "careerName": "Mobile Application Development",
      "category": "computer",
      "categoryName": "Computer Science & IT",
      "role": "student",
      "description": "Focuses on designing and developing applications for mobile devices and platforms.",
      "education": "Students can pursue Computer Science, Software Engineering or IT and specialize in mobile application development.",
      "skills": ["Programming", "UI Design", "Mobile Development", "Problem Solving"],
      "scope": "Provides pathways into Android, iOS, cross-platform and mobile software development.",
      "salaryRange": "Depends on platform, specialization and experience after graduation.",
    },
    {
      "careerName": "Game Development",
      "category": "computer",
      "categoryName": "Computer Science & IT",
      "role": "student",
      "description": "Combines programming, graphics and design to create interactive digital games.",
      "education": "Students can pursue Computer Science, Software Engineering, Game Development or related computing studies.",
      "skills": ["Programming", "Game Design", "3D Graphics", "Problem Solving"],
      "scope": "Provides pathways into game studios, interactive media, simulation and independent game development.",
      "salaryRange": "Depends on specialization, portfolio and experience after graduation.",
    },

    // ==========================================================
    // 2. ENGINEERING - 10
    // ==========================================================

    {
      "careerName": "Civil Engineering",
      "category": "engineering",
      "categoryName": "Engineering",
      "role": "student",
      "description": "Studies the design, construction and maintenance of buildings, roads, bridges and infrastructure.",
      "education": "After Intermediate or equivalent with relevant subjects, students can pursue a BS/BE degree in Civil Engineering.",
      "skills": ["Mathematics", "Physics", "Technical Drawing", "Problem Solving"],
      "scope": "Provides pathways into construction, infrastructure, structural design, transportation and engineering consultancy.",
      "salaryRange": "Depends on specialization, organization and experience after graduation.",
    },
    {
      "careerName": "Mechanical Engineering",
      "category": "engineering",
      "categoryName": "Engineering",
      "role": "student",
      "description": "Studies machines, mechanical systems, manufacturing and energy-related technologies.",
      "education": "After Intermediate or equivalent with relevant subjects, students can pursue a BS/BE degree in Mechanical Engineering.",
      "skills": ["Mathematics", "Physics", "CAD", "Problem Solving"],
      "scope": "Provides pathways into manufacturing, automotive, energy, design and industrial organizations.",
      "salaryRange": "Depends on specialization, industry and experience after graduation.",
    },
    {
      "careerName": "Electrical Engineering",
      "category": "engineering",
      "categoryName": "Engineering",
      "role": "student",
      "description": "Studies electrical systems, electronics, power technologies and control systems.",
      "education": "After Intermediate or equivalent with relevant subjects, students can pursue a BS/BE degree in Electrical Engineering.",
      "skills": ["Mathematics", "Physics", "Electronics", "Problem Solving"],
      "scope": "Provides pathways into power systems, electronics, automation, telecommunications and engineering industries.",
      "salaryRange": "Depends on specialization, industry and experience after graduation.",
    },
    {
      "careerName": "Electronics Engineering",
      "category": "engineering",
      "categoryName": "Engineering",
      "role": "student",
      "description": "Focuses on electronic circuits, devices, embedded systems and electronic technologies.",
      "education": "After Intermediate or equivalent with relevant subjects, students can pursue a BS/BE degree in Electronics Engineering.",
      "skills": ["Electronics", "Circuit Design", "Mathematics", "Problem Solving"],
      "scope": "Provides pathways into electronics, embedded systems, telecommunications, automation and technology industries.",
      "salaryRange": "Depends on specialization and experience after graduation.",
    },
    {
      "careerName": "Computer Engineering",
      "category": "engineering",
      "categoryName": "Engineering",
      "role": "student",
      "description": "Combines computer science and engineering to study hardware, software and computer systems.",
      "education": "After Intermediate or equivalent with relevant subjects, students can pursue a BS/BE degree in Computer Engineering.",
      "skills": ["Programming", "Digital Logic", "Computer Architecture", "Mathematics"],
      "scope": "Provides pathways into hardware, embedded systems, computer architecture and technology development.",
      "salaryRange": "Depends on specialization and experience after graduation.",
    },
    {
      "careerName": "Chemical Engineering",
      "category": "engineering",
      "categoryName": "Engineering",
      "role": "student",
      "description": "Studies industrial processes involving chemicals, materials, energy and manufacturing.",
      "education": "After Intermediate or equivalent with relevant subjects, students can pursue a BS/BE degree in Chemical Engineering.",
      "skills": ["Chemistry", "Mathematics", "Thermodynamics", "Problem Solving"],
      "scope": "Provides pathways into chemical, pharmaceutical, energy, food and manufacturing industries.",
      "salaryRange": "Depends on industry, specialization and experience after graduation.",
    },
    {
      "careerName": "Software Engineering",
      "category": "engineering",
      "categoryName": "Engineering",
      "role": "student",
      "description": "Applies engineering principles to the development, testing and management of software systems.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Software Engineering.",
      "skills": ["Programming", "Algorithms", "Software Design", "Problem Solving"],
      "scope": "Provides pathways into software houses, technology companies, startups and digital organizations.",
      "salaryRange": "Depends on specialization, skills and experience after graduation.",
    },
    {
      "careerName": "Mechatronics Engineering",
      "category": "engineering",
      "categoryName": "Engineering",
      "role": "student",
      "description": "Combines mechanical, electrical and computer engineering for automated and intelligent systems.",
      "education": "After Intermediate or equivalent with relevant subjects, students can pursue a BS/BE degree in Mechatronics Engineering.",
      "skills": ["Robotics", "Automation", "Electronics", "Programming"],
      "scope": "Provides pathways into robotics, industrial automation, manufacturing and smart systems.",
      "salaryRange": "Depends on specialization, industry and experience after graduation.",
    },
    {
      "careerName": "Petroleum Engineering",
      "category": "engineering",
      "categoryName": "Engineering",
      "role": "student",
      "description": "Studies exploration, extraction and production of oil and gas resources.",
      "education": "After Intermediate or equivalent with relevant subjects, students can pursue a BS/BE degree in Petroleum Engineering.",
      "skills": ["Mathematics", "Physics", "Geology", "Problem Solving"],
      "scope": "Provides pathways into oil and gas companies, energy organizations and petroleum engineering firms.",
      "salaryRange": "Depends on industry, specialization and experience after graduation.",
    },
    {
      "careerName": "Environmental Engineering",
      "category": "engineering",
      "categoryName": "Engineering",
      "role": "student",
      "description": "Applies engineering principles to environmental protection, pollution control and sustainability.",
      "education": "After Intermediate or equivalent with relevant subjects, students can pursue a BS/BE degree in Environmental Engineering.",
      "skills": ["Environmental Science", "Mathematics", "Problem Solving", "Sustainability"],
      "scope": "Provides pathways into environmental consulting, water management, waste management and sustainability projects.",
      "salaryRange": "Depends on organization, specialization and experience after graduation.",
    },

    // ==========================================================
    // 3. MEDICAL & HEALTHCARE - 10
    // ==========================================================

    {
      "careerName": "Medicine",
      "category": "medical",
      "categoryName": "Medical & Healthcare",
      "role": "student",
      "description": "Studies human health, disease, diagnosis, treatment and clinical care.",
      "education": "After Intermediate with relevant science subjects, students can pursue an MBBS or equivalent medical degree.",
      "skills": ["Biology", "Chemistry", "Communication", "Critical Thinking"],
      "scope": "Provides pathways into clinical medicine, hospitals, healthcare organizations and medical specialization.",
      "salaryRange": "Depends on specialization, workplace and experience after qualification.",
    },
    {
      "careerName": "Dentistry",
      "category": "medical",
      "categoryName": "Medical & Healthcare",
      "role": "student",
      "description": "Focuses on oral health, dental diagnosis, prevention and treatment.",
      "education": "After Intermediate with relevant science subjects, students can pursue a BDS or equivalent dental degree.",
      "skills": ["Biology", "Chemistry", "Clinical Skills", "Communication"],
      "scope": "Provides pathways into dental hospitals, clinics, healthcare organizations and private practice.",
      "salaryRange": "Depends on specialization, practice and experience after qualification.",
    },
    {
      "careerName": "Pharmacy",
      "category": "medical",
      "categoryName": "Medical & Healthcare",
      "role": "student",
      "description": "Studies medicines, drug development, pharmaceutical sciences and safe medication use.",
      "education": "After Intermediate with relevant science subjects, students can pursue a Pharm-D or related pharmacy degree.",
      "skills": ["Chemistry", "Biology", "Pharmacology", "Communication"],
      "scope": "Provides pathways into hospitals, pharmacies, pharmaceutical companies, research and regulatory organizations.",
      "salaryRange": "Depends on specialization, organization and experience after qualification.",
    },
    {
      "careerName": "Nursing",
      "category": "medical",
      "categoryName": "Medical & Healthcare",
      "role": "student",
      "description": "Focuses on patient care, health promotion, clinical practice and healthcare support.",
      "education": "After Intermediate with relevant science subjects, students can pursue a BS Nursing or approved nursing program.",
      "skills": ["Biology", "Patient Care", "Communication", "Clinical Skills"],
      "scope": "Provides pathways into hospitals, clinics, community healthcare and specialized nursing services.",
      "salaryRange": "Depends on qualification, specialization, workplace and experience.",
    },
    {
      "careerName": "Physiotherapy",
      "category": "medical",
      "categoryName": "Medical & Healthcare",
      "role": "student",
      "description": "Studies physical rehabilitation, movement, exercise therapy and recovery from injuries and conditions.",
      "education": "After Intermediate with relevant science subjects, students can pursue a Doctor of Physical Therapy or related degree.",
      "skills": ["Biology", "Exercise Therapy", "Patient Assessment", "Communication"],
      "scope": "Provides pathways into hospitals, rehabilitation centers, clinics and sports organizations.",
      "salaryRange": "Depends on specialization, workplace and experience after qualification.",
    },
    {
      "careerName": "Medical Laboratory Science",
      "category": "medical",
      "categoryName": "Medical & Healthcare",
      "role": "student",
      "description": "Studies laboratory testing, biological samples and scientific methods used to support healthcare decisions.",
      "education": "After Intermediate with relevant science subjects, students can pursue a BS degree in Medical Laboratory Science or related field.",
      "skills": ["Biology", "Chemistry", "Laboratory Work", "Data Analysis"],
      "scope": "Provides pathways into hospitals, diagnostic laboratories, research centers and healthcare industries.",
      "salaryRange": "Depends on specialization, organization and experience after qualification.",
    },
    {
      "careerName": "Public Health",
      "category": "medical",
      "categoryName": "Medical & Healthcare",
      "role": "student",
      "description": "Focuses on improving health outcomes at community and population levels through prevention and health programs.",
      "education": "Students can pursue a BS degree in Public Health or a related healthcare field after Intermediate.",
      "skills": ["Biology", "Research", "Statistics", "Communication"],
      "scope": "Provides pathways into government health programs, NGOs, healthcare organizations and community health initiatives.",
      "salaryRange": "Depends on qualification, organization and experience.",
    },
    {
      "careerName": "Nutrition & Dietetics",
      "category": "medical",
      "categoryName": "Medical & Healthcare",
      "role": "student",
      "description": "Studies nutrition, food science and dietary planning to support health and wellbeing.",
      "education": "After Intermediate with relevant science subjects, students can pursue a degree in Nutrition and Dietetics.",
      "skills": ["Biology", "Nutrition", "Communication", "Health Assessment"],
      "scope": "Provides pathways into hospitals, wellness centers, clinics, food organizations and community health programs.",
      "salaryRange": "Depends on specialization, workplace and experience after qualification.",
    },
    {
      "careerName": "Medical Imaging",
      "category": "medical",
      "categoryName": "Medical & Healthcare",
      "role": "student",
      "description": "Studies medical imaging technologies used to support diagnosis and patient care.",
      "education": "After Intermediate with relevant science subjects, students can pursue a degree in Radiologic Technology, Medical Imaging or related field.",
      "skills": ["Physics", "Biology", "Medical Imaging", "Patient Care"],
      "scope": "Provides pathways into hospitals, diagnostic centers and medical imaging departments.",
      "salaryRange": "Depends on qualification, specialization and institution.",
    },
    {
      "careerName": "Medical Biotechnology",
      "category": "medical",
      "categoryName": "Medical & Healthcare",
      "role": "student",
      "description": "Combines biology and technology to study medical research, diagnostics and biotechnology applications.",
      "education": "After Intermediate with relevant science subjects, students can pursue a BS degree in Biotechnology or Medical Biotechnology.",
      "skills": ["Biology", "Chemistry", "Laboratory Research", "Data Analysis"],
      "scope": "Provides pathways into biotechnology companies, medical research, laboratories and healthcare research organizations.",
      "salaryRange": "Depends on specialization, organization and experience after graduation.",
    },

    // ==========================================================
    // 4. BUSINESS & MANAGEMENT - 10
    // ==========================================================

    {
      "careerName": "Business Administration",
      "category": "business",
      "categoryName": "Business & Management",
      "role": "student",
      "description": "Provides a broad foundation in business operations, management, marketing, finance and entrepreneurship.",
      "education": "After Intermediate or equivalent, students can pursue a BBA or BS degree in Business Administration.",
      "skills": ["Communication", "Management", "Problem Solving", "Business Knowledge"],
      "scope": "Provides pathways into management, marketing, operations, sales, business development and entrepreneurship.",
      "salaryRange": "Depends on specialization, organization and experience after graduation.",
    },
    {
      "careerName": "Marketing",
      "category": "business",
      "categoryName": "Business & Management",
      "role": "student",
      "description": "Studies how organizations promote products, understand customers and develop marketing strategies.",
      "education": "After Intermediate or equivalent, students can pursue a BBA or BS degree with specialization in Marketing.",
      "skills": ["Communication", "Market Research", "Creativity", "Digital Marketing"],
      "scope": "Provides pathways into marketing agencies, companies, startups, advertising and digital marketing.",
      "salaryRange": "Depends on specialization, organization and experience after graduation.",
    },
    {
      "careerName": "Human Resource Management",
      "category": "business",
      "categoryName": "Business & Management",
      "role": "student",
      "description": "Studies recruitment, employee development, organizational behavior and human resource operations.",
      "education": "After Intermediate or equivalent, students can pursue a BBA or BS degree in Human Resource Management.",
      "skills": ["Communication", "Recruitment", "Leadership", "Organization"],
      "scope": "Provides pathways into HR departments, recruitment firms, training organizations and corporate management.",
      "salaryRange": "Depends on organization, specialization and experience after graduation.",
    },
    {
      "careerName": "Entrepreneurship",
      "category": "business",
      "categoryName": "Business & Management",
      "role": "student",
      "description": "Focuses on identifying business opportunities, developing ideas and building new ventures.",
      "education": "After Intermediate or equivalent, students can pursue a BBA or degree with a specialization in Entrepreneurship.",
      "skills": ["Business Planning", "Leadership", "Creativity", "Decision Making"],
      "scope": "Provides pathways into startups, family businesses, innovation projects and new business ventures.",
      "salaryRange": "Depends on business performance and entrepreneurial success.",
    },
    {
      "careerName": "Supply Chain Management",
      "category": "business",
      "categoryName": "Business & Management",
      "role": "student",
      "description": "Studies the movement of products, materials and resources from suppliers to customers.",
      "education": "After Intermediate or equivalent, students can pursue a BS/BBA degree in Supply Chain Management.",
      "skills": ["Planning", "Logistics", "Inventory Management", "Analysis"],
      "scope": "Provides pathways into manufacturing, retail, logistics, procurement and distribution organizations.",
      "salaryRange": "Depends on industry, specialization and experience after graduation.",
    },
    {
      "careerName": "Operations Management",
      "category": "business",
      "categoryName": "Business & Management",
      "role": "student",
      "description": "Studies how organizations manage processes, resources and daily operations efficiently.",
      "education": "After Intermediate or equivalent, students can pursue a BBA or BS degree in Management or Operations.",
      "skills": ["Planning", "Process Management", "Problem Solving", "Leadership"],
      "scope": "Provides pathways into operations, production, services, logistics and organizational management.",
      "salaryRange": "Depends on industry, organization and experience after graduation.",
    },
    {
      "careerName": "Business Analytics",
      "category": "business",
      "categoryName": "Business & Management",
      "role": "student",
      "description": "Combines business knowledge and data analysis to support organizational decisions.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Business Analytics or a related field.",
      "skills": ["Data Analysis", "Statistics", "Excel", "Problem Solving"],
      "scope": "Provides pathways into business intelligence, consulting, operations and data-driven management.",
      "salaryRange": "Depends on specialization, organization and experience after graduation.",
    },
    {
      "careerName": "International Business",
      "category": "business",
      "categoryName": "Business & Management",
      "role": "student",
      "description": "Studies business activities, markets and management across different countries and regions.",
      "education": "After Intermediate or equivalent, students can pursue a BBA or BS degree in International Business.",
      "skills": ["Communication", "Business Knowledge", "Market Research", "Negotiation"],
      "scope": "Provides pathways into multinational companies, international trade, consulting and global business operations.",
      "salaryRange": "Depends on specialization, organization and experience after graduation.",
    },
    {
      "careerName": "Management",
      "category": "business",
      "categoryName": "Business & Management",
      "role": "student",
      "description": "Studies leadership, organizational planning, decision making and management practices.",
      "education": "After Intermediate or equivalent, students can pursue a BBA or BS degree in Management.",
      "skills": ["Leadership", "Communication", "Planning", "Decision Making"],
      "scope": "Provides pathways into administrative, management, operations and organizational roles.",
      "salaryRange": "Depends on specialization, organization and experience after graduation.",
    },
    {
      "careerName": "E-Commerce",
      "category": "business",
      "categoryName": "Business & Management",
      "role": "student",
      "description": "Studies online business models, digital commerce, customer management and electronic marketplaces.",
      "education": "After Intermediate or equivalent, students can pursue Business, Marketing, IT or E-Commerce related studies.",
      "skills": ["Digital Marketing", "Business", "Communication", "Technology"],
      "scope": "Provides pathways into online businesses, e-commerce companies, digital marketplaces and entrepreneurship.",
      "salaryRange": "Depends on specialization, organization and business performance.",
    },

    // ==========================================================
    // 5. FINANCE & ACCOUNTING - 10
    // ==========================================================

    {
      "careerName": "Accounting & Finance",
      "category": "finance",
      "categoryName": "Finance & Accounting",
      "role": "student",
      "description": "Studies financial records, accounting principles, financial management and business finance.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Accounting & Finance.",
      "skills": ["Accounting", "Mathematics", "Excel", "Financial Analysis"],
      "scope": "Provides pathways into accounting firms, banks, companies, financial institutions and corporate finance.",
      "salaryRange": "Depends on specialization, organization and experience after graduation.",
    },
    {
      "careerName": "Accounting",
      "category": "finance",
      "categoryName": "Finance & Accounting",
      "role": "student",
      "description": "Focuses on recording, analyzing and reporting financial information for organizations.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Accounting or a related field.",
      "skills": ["Accounting", "Bookkeeping", "Excel", "Financial Reporting"],
      "scope": "Provides pathways into accounting firms, businesses, banks and government organizations.",
      "salaryRange": "Depends on qualification, organization and experience.",
    },
    {
      "careerName": "Finance",
      "category": "finance",
      "categoryName": "Finance & Accounting",
      "role": "student",
      "description": "Studies financial management, investments, markets and financial decision making.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Finance.",
      "skills": ["Financial Analysis", "Mathematics", "Economics", "Excel"],
      "scope": "Provides pathways into banks, investment firms, corporations and financial institutions.",
      "salaryRange": "Depends on specialization, organization and experience.",
    },
    {
      "careerName": "Banking & Finance",
      "category": "finance",
      "categoryName": "Finance & Accounting",
      "role": "student",
      "description": "Studies banking operations, financial services, markets and financial management.",
      "education": "After Intermediate or equivalent, students can pursue a degree in Banking & Finance or related field.",
      "skills": ["Finance", "Economics", "Communication", "Analysis"],
      "scope": "Provides pathways into banks, financial institutions, investment organizations and financial services.",
      "salaryRange": "Depends on specialization, institution and experience.",
    },
    {
      "careerName": "Islamic Banking & Finance",
      "category": "finance",
      "categoryName": "Finance & Accounting",
      "role": "student",
      "description": "Studies financial management and banking practices based on Islamic finance principles.",
      "education": "After Intermediate or equivalent, students can pursue a degree in Islamic Banking & Finance.",
      "skills": ["Finance", "Accounting", "Economics", "Analytical Thinking"],
      "scope": "Provides pathways into Islamic banks, financial institutions, Shariah-compliant financial services and research.",
      "salaryRange": "Depends on specialization, organization and experience.",
    },
    {
      "careerName": "Economics",
      "category": "finance",
      "categoryName": "Finance & Accounting",
      "role": "student",
      "description": "Studies how individuals, businesses and governments use resources and make economic decisions.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Economics.",
      "skills": ["Mathematics", "Statistics", "Analysis", "Research"],
      "scope": "Provides pathways into banking, research, policy, consulting, government and business analysis.",
      "salaryRange": "Depends on specialization, organization and experience.",
    },
    {
      "careerName": "Actuarial Science",
      "category": "finance",
      "categoryName": "Finance & Accounting",
      "role": "student",
      "description": "Uses mathematics, statistics and financial theory to analyze risk and uncertainty.",
      "education": "After Intermediate or equivalent, students can pursue a degree in Actuarial Science or related quantitative field.",
      "skills": ["Mathematics", "Statistics", "Risk Analysis", "Problem Solving"],
      "scope": "Provides pathways into insurance, risk management, finance, investment and actuarial organizations.",
      "salaryRange": "Depends on professional qualifications, specialization and experience.",
    },
    {
      "careerName": "Taxation",
      "category": "finance",
      "categoryName": "Finance & Accounting",
      "role": "student",
      "description": "Studies taxation systems, tax planning, compliance and financial regulations.",
      "education": "Students can pursue Accounting, Finance, Business or related studies and specialize in taxation.",
      "skills": ["Accounting", "Taxation", "Law", "Analysis"],
      "scope": "Provides pathways into accounting firms, tax advisory, corporate finance and government tax organizations.",
      "salaryRange": "Depends on qualification, specialization and experience.",
    },
    {
      "careerName": "Auditing",
      "category": "finance",
      "categoryName": "Finance & Accounting",
      "role": "student",
      "description": "Studies methods for examining financial records, controls and organizational compliance.",
      "education": "After Intermediate or equivalent, students can pursue Accounting & Finance or related studies and specialize in auditing.",
      "skills": ["Accounting", "Analysis", "Attention to Detail", "Financial Reporting"],
      "scope": "Provides pathways into audit firms, accounting departments, financial institutions and corporate compliance.",
      "salaryRange": "Depends on professional qualification, organization and experience.",
    },
    {
      "careerName": "Financial Management",
      "category": "finance",
      "categoryName": "Finance & Accounting",
      "role": "student",
      "description": "Focuses on managing financial resources, budgeting, investment decisions and business finance.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Finance or Financial Management.",
      "skills": ["Financial Planning", "Analysis", "Excel", "Decision Making"],
      "scope": "Provides pathways into corporate finance, banking, investment and financial management.",
      "salaryRange": "Depends on specialization, organization and experience.",
    },

    // ==========================================================
    // 6. LAW - 10
    // ==========================================================

    {
      "careerName": "Law",
      "category": "law",
      "categoryName": "Law",
      "role": "student",
      "description": "Studies legal principles, rights, responsibilities and systems of justice.",
      "education": "After Intermediate or equivalent, students can pursue an LLB or other approved law degree.",
      "skills": ["Legal Research", "Communication", "Critical Thinking", "Argumentation"],
      "scope": "Provides pathways into legal practice, corporate law, government, courts and legal organizations.",
      "salaryRange": "Depends on specialization, qualification and experience.",
    },
    {
      "careerName": "Corporate Law",
      "category": "law",
      "categoryName": "Law",
      "role": "student",
      "description": "Focuses on legal matters involving companies, businesses, contracts and commercial transactions.",
      "education": "Students can pursue an LLB and later specialize in corporate and commercial law.",
      "skills": ["Legal Research", "Contract Law", "Negotiation", "Communication"],
      "scope": "Provides pathways into corporations, law firms and commercial legal practice.",
      "salaryRange": "Depends on specialization, firm and experience.",
    },
    {
      "careerName": "Criminal Law",
      "category": "law",
      "categoryName": "Law",
      "role": "student",
      "description": "Studies laws and legal procedures related to criminal offenses and justice.",
      "education": "Students can pursue an LLB and develop specialization in criminal law and related legal practice.",
      "skills": ["Legal Research", "Critical Thinking", "Communication", "Argumentation"],
      "scope": "Provides pathways into law firms, courts, prosecution and criminal legal practice.",
      "salaryRange": "Depends on qualification, specialization and experience.",
    },
    {
      "careerName": "Civil Law",
      "category": "law",
      "categoryName": "Law",
      "role": "student",
      "description": "Studies legal matters involving disputes between individuals, organizations and other parties.",
      "education": "Students can pursue an LLB and specialize in civil legal matters.",
      "skills": ["Legal Research", "Analysis", "Communication", "Negotiation"],
      "scope": "Provides pathways into law firms, courts, legal consultancy and private practice.",
      "salaryRange": "Depends on specialization, practice and experience.",
    },
    {
      "careerName": "Constitutional Law",
      "category": "law",
      "categoryName": "Law",
      "role": "student",
      "description": "Studies constitutional principles, government structures, rights and public law.",
      "education": "Students can pursue an LLB and study constitutional and public law as an area of specialization.",
      "skills": ["Legal Research", "Critical Thinking", "Analysis", "Writing"],
      "scope": "Provides pathways into legal practice, public institutions, research and constitutional law.",
      "salaryRange": "Depends on qualification, specialization and experience.",
    },
    {
      "careerName": "International Law",
      "category": "law",
      "categoryName": "Law",
      "role": "student",
      "description": "Studies legal relationships and principles involving countries, international organizations and global matters.",
      "education": "Students can pursue an LLB and later specialize in international law.",
      "skills": ["Legal Research", "International Relations", "Communication", "Analysis"],
      "scope": "Provides pathways into international organizations, NGOs, legal research and international legal practice.",
      "salaryRange": "Depends on specialization, organization and experience.",
    },
    {
      "careerName": "Human Rights Law",
      "category": "law",
      "categoryName": "Law",
      "role": "student",
      "description": "Focuses on legal principles protecting fundamental rights and freedoms.",
      "education": "Students can pursue an LLB and specialize in human rights and related public-interest law.",
      "skills": ["Legal Research", "Communication", "Advocacy", "Critical Thinking"],
      "scope": "Provides pathways into NGOs, human rights organizations, legal aid and public-interest legal work.",
      "salaryRange": "Depends on organization, specialization and experience.",
    },
    {
      "careerName": "Intellectual Property Law",
      "category": "law",
      "categoryName": "Law",
      "role": "student",
      "description": "Studies legal protection of inventions, brands, creative works and other intellectual property.",
      "education": "Students can pursue an LLB and develop specialization in intellectual property law.",
      "skills": ["Legal Research", "Analysis", "Writing", "Communication"],
      "scope": "Provides pathways into law firms, technology companies, creative industries and intellectual property practice.",
      "salaryRange": "Depends on specialization, firm and experience.",
    },
    {
      "careerName": "Legal Studies",
      "category": "law",
      "categoryName": "Law",
      "role": "student",
      "description": "Provides broad academic knowledge of legal systems, legal research and principles of law.",
      "education": "Students can pursue an undergraduate law degree or related legal studies program.",
      "skills": ["Research", "Writing", "Critical Thinking", "Communication"],
      "scope": "Provides pathways into legal practice, legal research, compliance and public-sector organizations.",
      "salaryRange": "Depends on further qualification, specialization and experience.",
    },
    {
      "careerName": "Legal & Compliance",
      "category": "law",
      "categoryName": "Law",
      "role": "student",
      "description": "Combines legal knowledge with organizational compliance, regulations and risk awareness.",
      "education": "Students can pursue Law, Business or related studies and specialize in compliance.",
      "skills": ["Legal Research", "Compliance", "Analysis", "Attention to Detail"],
      "scope": "Provides pathways into banks, corporations, financial institutions, regulatory organizations and compliance departments.",
      "salaryRange": "Depends on qualification, organization and experience.",
    },

    // ==========================================================
    // 7. EDUCATION - 10
    // ==========================================================

    {
      "careerName": "Education",
      "category": "education",
      "categoryName": "Education",
      "role": "student",
      "description": "Studies teaching, learning, educational psychology and methods for supporting students.",
      "education": "After Intermediate or equivalent, students can pursue a BS/B.Ed degree in Education.",
      "skills": ["Communication", "Teaching", "Planning", "Research"],
      "scope": "Provides pathways into teaching, educational administration, curriculum development and training.",
      "salaryRange": "Depends on qualification, institution and experience.",
    },
    {
      "careerName": "Early Childhood Education",
      "category": "education",
      "categoryName": "Education",
      "role": "student",
      "description": "Focuses on the development, learning and educational needs of young children.",
      "education": "Students can pursue an undergraduate degree or specialization in Early Childhood Education after Intermediate.",
      "skills": ["Teaching", "Communication", "Child Development", "Creativity"],
      "scope": "Provides pathways into preschools, schools, childcare organizations and early learning programs.",
      "salaryRange": "Depends on qualification, institution and experience.",
    },
    {
      "careerName": "Special Education",
      "category": "education",
      "categoryName": "Education",
      "role": "student",
      "description": "Studies teaching strategies and educational support for students with diverse learning needs.",
      "education": "Students can pursue a BS degree in Special Education after Intermediate or equivalent.",
      "skills": ["Teaching", "Communication", "Patience", "Learning Support"],
      "scope": "Provides pathways into schools, special education centers, NGOs and educational support services.",
      "salaryRange": "Depends on qualification, institution and experience.",
    },
    {
      "careerName": "Educational Psychology",
      "category": "education",
      "categoryName": "Education",
      "role": "student",
      "description": "Studies how students learn, develop and respond to educational environments.",
      "education": "Students can pursue Education or Psychology and specialize in educational psychology through further study.",
      "skills": ["Psychology", "Research", "Communication", "Assessment"],
      "scope": "Provides pathways into educational research, student support, academic services and learning programs.",
      "salaryRange": "Depends on qualification, organization and experience.",
    },
    {
      "careerName": "Educational Technology",
      "category": "education",
      "categoryName": "Education",
      "role": "student",
      "description": "Combines education and technology to develop modern digital learning experiences.",
      "education": "Students can pursue Education, Educational Technology or related undergraduate studies.",
      "skills": ["Technology", "Teaching", "Digital Learning", "Communication"],
      "scope": "Provides pathways into e-learning, educational technology companies, digital content and training.",
      "salaryRange": "Depends on specialization, organization and experience.",
    },
    {
      "careerName": "Curriculum Studies",
      "category": "education",
      "categoryName": "Education",
      "role": "student",
      "description": "Studies how educational curricula, courses and learning materials are designed and evaluated.",
      "education": "Students can pursue Education and later specialize in curriculum development and educational planning.",
      "skills": ["Research", "Writing", "Planning", "Education"],
      "scope": "Provides pathways into schools, universities, educational publishers and curriculum projects.",
      "salaryRange": "Depends on qualification, organization and experience.",
    },
    {
      "careerName": "Educational Leadership",
      "category": "education",
      "categoryName": "Education",
      "role": "student",
      "description": "Focuses on leadership, administration and management within educational organizations.",
      "education": "Students can pursue Education, Management or related studies and specialize in educational leadership.",
      "skills": ["Leadership", "Planning", "Communication", "Management"],
      "scope": "Provides pathways into school administration, academic coordination and education management.",
      "salaryRange": "Depends on qualification, institution and experience.",
    },
    {
      "careerName": "English Education",
      "category": "education",
      "categoryName": "Education",
      "role": "student",
      "description": "Combines English language studies with teaching methods and educational practice.",
      "education": "After Intermediate or equivalent, students can pursue a degree in English, Education or English Education.",
      "skills": ["English", "Communication", "Writing", "Teaching"],
      "scope": "Provides pathways into schools, colleges, language centers, content development and education.",
      "salaryRange": "Depends on qualification, institution and experience.",
    },
    {
      "careerName": "Mathematics Education",
      "category": "education",
      "categoryName": "Education",
      "role": "student",
      "description": "Combines mathematics knowledge with teaching methods and educational practice.",
      "education": "After Intermediate or equivalent, students can pursue Mathematics, Education or Mathematics Education.",
      "skills": ["Mathematics", "Teaching", "Problem Solving", "Communication"],
      "scope": "Provides pathways into schools, colleges, tutoring, educational content and academic services.",
      "salaryRange": "Depends on qualification, institution and experience.",
    },
    {
      "careerName": "Teacher Education",
      "category": "education",
      "categoryName": "Education",
      "role": "student",
      "description": "Prepares students with teaching knowledge, classroom methods and professional educational practices.",
      "education": "After Intermediate or equivalent, students can pursue a B.Ed or related teacher education program.",
      "skills": ["Teaching", "Classroom Management", "Communication", "Lesson Planning"],
      "scope": "Provides pathways into schools, colleges, tutoring centers and educational institutions.",
      "salaryRange": "Depends on qualification, institution and experience.",
    },

    // ==========================================================
    // 8. PSYCHOLOGY & SOCIAL SCIENCES - 10
    // ==========================================================

    {
      "careerName": "Psychology",
      "category": "psychology_social_sciences",
      "categoryName": "Psychology & Social Sciences",
      "role": "student",
      "description": "Studies human behavior, mental processes, development and psychological principles.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Psychology.",
      "skills": ["Psychology", "Research", "Communication", "Critical Thinking"],
      "scope": "Provides pathways into counseling, education, organizational settings, research and further professional training.",
      "salaryRange": "Depends on further qualification, specialization and experience.",
    },
    {
      "careerName": "Sociology",
      "category": "psychology_social_sciences",
      "categoryName": "Psychology & Social Sciences",
      "role": "student",
      "description": "Studies society, social relationships, institutions and patterns of human interaction.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Sociology.",
      "skills": ["Research", "Communication", "Social Analysis", "Critical Thinking"],
      "scope": "Provides pathways into research, NGOs, community development, education and social organizations.",
      "salaryRange": "Depends on specialization, organization and experience.",
    },
    {
      "careerName": "Political Science",
      "category": "psychology_social_sciences",
      "categoryName": "Psychology & Social Sciences",
      "role": "student",
      "description": "Studies government, political systems, public institutions and political ideas.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Political Science.",
      "skills": ["Research", "Analysis", "Communication", "Writing"],
      "scope": "Provides pathways into government, research, policy organizations, education and public affairs.",
      "salaryRange": "Depends on organization, qualification and experience.",
    },
    {
      "careerName": "International Relations",
      "category": "psychology_social_sciences",
      "categoryName": "Psychology & Social Sciences",
      "role": "student",
      "description": "Studies relationships between countries, international organizations and global political issues.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in International Relations.",
      "skills": ["Research", "Communication", "Analysis", "Current Affairs"],
      "scope": "Provides pathways into government, diplomacy-related work, NGOs, international organizations and research.",
      "salaryRange": "Depends on organization, qualification and experience.",
    },
    {
      "careerName": "Social Work",
      "category": "psychology_social_sciences",
      "categoryName": "Psychology & Social Sciences",
      "role": "student",
      "description": "Studies social issues and methods for supporting individuals, families and communities.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Social Work.",
      "skills": ["Communication", "Community Work", "Research", "Empathy"],
      "scope": "Provides pathways into NGOs, community programs, social services and development organizations.",
      "salaryRange": "Depends on organization, qualification and experience.",
    },
    {
      "careerName": "Anthropology",
      "category": "psychology_social_sciences",
      "categoryName": "Psychology & Social Sciences",
      "role": "student",
      "description": "Studies human cultures, societies, communities and human development.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Anthropology.",
      "skills": ["Research", "Observation", "Communication", "Cultural Analysis"],
      "scope": "Provides pathways into research, development organizations, NGOs, cultural institutions and academia.",
      "salaryRange": "Depends on specialization, organization and experience.",
    },
    {
      "careerName": "Criminology",
      "category": "psychology_social_sciences",
      "categoryName": "Psychology & Social Sciences",
      "role": "student",
      "description": "Studies crime, criminal behavior, justice systems and social factors related to crime.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Criminology or related social science.",
      "skills": ["Research", "Critical Thinking", "Analysis", "Communication"],
      "scope": "Provides pathways into research, justice-related organizations, law enforcement support and social services.",
      "salaryRange": "Depends on organization, specialization and experience.",
    },
    {
      "careerName": "Development Studies",
      "category": "psychology_social_sciences",
      "categoryName": "Psychology & Social Sciences",
      "role": "student",
      "description": "Studies social and economic development, poverty, communities and development policies.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Development Studies.",
      "skills": ["Research", "Data Analysis", "Communication", "Project Planning"],
      "scope": "Provides pathways into NGOs, development agencies, research organizations and community development projects.",
      "salaryRange": "Depends on organization, qualification and experience.",
    },
    {
      "careerName": "Gender Studies",
      "category": "psychology_social_sciences",
      "categoryName": "Psychology & Social Sciences",
      "role": "student",
      "description": "Studies gender, society, culture, social relationships and related social issues.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Gender Studies.",
      "skills": ["Research", "Communication", "Social Analysis", "Critical Thinking"],
      "scope": "Provides pathways into research, NGOs, development organizations, education and social policy.",
      "salaryRange": "Depends on organization, qualification and experience.",
    },
    {
      "careerName": "Public Administration",
      "category": "psychology_social_sciences",
      "categoryName": "Psychology & Social Sciences",
      "role": "student",
      "description": "Studies public organizations, administration, governance and delivery of public services.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Public Administration.",
      "skills": ["Management", "Communication", "Policy Analysis", "Planning"],
      "scope": "Provides pathways into government organizations, public-sector administration, NGOs and policy organizations.",
      "salaryRange": "Depends on organization, qualification and experience.",
    },

    // ==========================================================
    // 9. SCIENCE & RESEARCH - 10
    // ==========================================================

    {
      "careerName": "Physics",
      "category": "science_research",
      "categoryName": "Science & Research",
      "role": "student",
      "description": "Studies matter, energy, motion, forces and the fundamental principles of the physical world.",
      "education": "After Intermediate or equivalent with relevant science subjects, students can pursue a BS degree in Physics.",
      "skills": ["Physics", "Mathematics", "Research", "Problem Solving"],
      "scope": "Provides pathways into research, education, technology, laboratories and scientific organizations.",
      "salaryRange": "Depends on specialization, qualification and organization.",
    },
    {
      "careerName": "Chemistry",
      "category": "science_research",
      "categoryName": "Science & Research",
      "role": "student",
      "description": "Studies chemical substances, reactions, materials and laboratory processes.",
      "education": "After Intermediate or equivalent with relevant science subjects, students can pursue a BS degree in Chemistry.",
      "skills": ["Chemistry", "Laboratory Work", "Research", "Analysis"],
      "scope": "Provides pathways into laboratories, pharmaceuticals, manufacturing, education and scientific research.",
      "salaryRange": "Depends on specialization, industry and experience.",
    },
    {
      "careerName": "Biology",
      "category": "science_research",
      "categoryName": "Science & Research",
      "role": "student",
      "description": "Studies living organisms, biological systems, cells and life processes.",
      "education": "After Intermediate or equivalent with relevant science subjects, students can pursue a BS degree in Biology or Biological Sciences.",
      "skills": ["Biology", "Research", "Laboratory Work", "Observation"],
      "scope": "Provides pathways into research, laboratories, education, biotechnology and environmental science.",
      "salaryRange": "Depends on specialization, organization and experience.",
    },
    {
      "careerName": "Mathematics",
      "category": "science_research",
      "categoryName": "Science & Research",
      "role": "student",
      "description": "Studies mathematical concepts, structures, logic and quantitative problem solving.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Mathematics.",
      "skills": ["Mathematics", "Logical Thinking", "Problem Solving", "Analysis"],
      "scope": "Provides pathways into education, research, data analysis, finance and quantitative careers.",
      "salaryRange": "Depends on specialization, organization and experience.",
    },
    {
      "careerName": "Statistics",
      "category": "science_research",
      "categoryName": "Science & Research",
      "role": "student",
      "description": "Studies data collection, statistical methods, probability and quantitative analysis.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Statistics.",
      "skills": ["Statistics", "Mathematics", "Data Analysis", "Research"],
      "scope": "Provides pathways into data analysis, research, finance, healthcare and business analytics.",
      "salaryRange": "Depends on specialization, organization and experience.",
    },
    {
      "careerName": "Biotechnology",
      "category": "science_research",
      "categoryName": "Science & Research",
      "role": "student",
      "description": "Uses biological systems and technologies to develop useful products, processes and scientific applications.",
      "education": "After Intermediate or equivalent with relevant science subjects, students can pursue a BS degree in Biotechnology.",
      "skills": ["Biology", "Chemistry", "Laboratory Research", "Data Analysis"],
      "scope": "Provides pathways into biotechnology, healthcare, agriculture, food and research organizations.",
      "salaryRange": "Depends on specialization, industry and experience.",
    },
    {
      "careerName": "Environmental Science",
      "category": "science_research",
      "categoryName": "Science & Research",
      "role": "student",
      "description": "Studies the environment, ecosystems, pollution, conservation and sustainability.",
      "education": "After Intermediate or equivalent with relevant subjects, students can pursue a BS degree in Environmental Science.",
      "skills": ["Environmental Science", "Research", "Data Analysis", "Sustainability"],
      "scope": "Provides pathways into environmental organizations, research, consulting, conservation and government programs.",
      "salaryRange": "Depends on specialization, organization and experience.",
    },
    {
      "careerName": "Geology",
      "category": "science_research",
      "categoryName": "Science & Research",
      "role": "student",
      "description": "Studies the Earth, rocks, minerals, geological processes and natural resources.",
      "education": "After Intermediate or equivalent with relevant science subjects, students can pursue a BS degree in Geology.",
      "skills": ["Geology", "Earth Science", "Research", "Field Work"],
      "scope": "Provides pathways into mining, petroleum, environmental consulting, research and geological organizations.",
      "salaryRange": "Depends on industry, specialization and experience.",
    },
    {
      "careerName": "Astronomy",
      "category": "science_research",
      "categoryName": "Science & Research",
      "role": "student",
      "description": "Studies stars, planets, galaxies and the physical processes of the universe.",
      "education": "Students can pursue Physics, Astronomy or related science studies after Intermediate.",
      "skills": ["Physics", "Mathematics", "Research", "Data Analysis"],
      "scope": "Provides pathways into scientific research, education, observatories and advanced space-related study.",
      "salaryRange": "Depends on qualification, research field and organization.",
    },
    {
      "careerName": "Food Science",
      "category": "science_research",
      "categoryName": "Science & Research",
      "role": "student",
      "description": "Studies food composition, safety, quality, processing and food technology.",
      "education": "After Intermediate or equivalent with relevant science subjects, students can pursue a BS degree in Food Science or related field.",
      "skills": ["Chemistry", "Biology", "Food Safety", "Laboratory Work"],
      "scope": "Provides pathways into food industries, quality control, laboratories, research and food safety organizations.",
      "salaryRange": "Depends on specialization, industry and experience.",
    },

    // ==========================================================
    // 10. ARTS & DESIGN - 10
    // ==========================================================

    {
      "careerName": "Fine Arts",
      "category": "arts_design",
      "categoryName": "Arts & Design",
      "role": "student",
      "description": "Studies visual art, drawing, painting, creative expression and artistic techniques.",
      "education": "After Intermediate or equivalent, students can pursue a BFA or related undergraduate degree in Fine Arts.",
      "skills": ["Drawing", "Painting", "Creativity", "Visual Communication"],
      "scope": "Provides pathways into art, galleries, education, illustration and independent creative work.",
      "salaryRange": "Depends on specialization, portfolio and experience.",
    },
    {
      "careerName": "Graphic Design",
      "category": "arts_design",
      "categoryName": "Arts & Design",
      "role": "student",
      "description": "Focuses on creating visual content for digital and print communication.",
      "education": "Students can pursue a degree in Graphic Design, Visual Communication or related field after Intermediate.",
      "skills": ["Graphic Design", "Typography", "Creativity", "Visual Communication"],
      "scope": "Provides pathways into design agencies, companies, advertising, digital media and freelance design.",
      "salaryRange": "Depends on portfolio, specialization and experience.",
    },
    {
      "careerName": "Fashion Design",
      "category": "arts_design",
      "categoryName": "Arts & Design",
      "role": "student",
      "description": "Studies clothing design, textiles, fashion concepts and creative product development.",
      "education": "After Intermediate or equivalent, students can pursue a degree in Fashion Design or related field.",
      "skills": ["Fashion Design", "Creativity", "Textiles", "Drawing"],
      "scope": "Provides pathways into fashion brands, textile companies, design studios and entrepreneurship.",
      "salaryRange": "Depends on portfolio, specialization and business performance.",
    },
    {
      "careerName": "Interior Design",
      "category": "arts_design",
      "categoryName": "Arts & Design",
      "role": "student",
      "description": "Focuses on planning and designing functional and visually appealing interior spaces.",
      "education": "After Intermediate or equivalent, students can pursue a degree in Interior Design or related field.",
      "skills": ["Design", "Creativity", "Technical Drawing", "Space Planning"],
      "scope": "Provides pathways into design studios, architecture firms, construction projects and independent practice.",
      "salaryRange": "Depends on specialization, portfolio and experience.",
    },
    {
      "careerName": "Architecture",
      "category": "arts_design",
      "categoryName": "Arts & Design",
      "role": "student",
      "description": "Studies the design, planning and development of buildings and physical spaces.",
      "education": "After Intermediate or equivalent with relevant subjects, students can pursue a professional degree in Architecture.",
      "skills": ["Design", "Drawing", "Mathematics", "Spatial Thinking"],
      "scope": "Provides pathways into architecture firms, construction, urban projects and design practice.",
      "salaryRange": "Depends on qualification, specialization and experience.",
    },
    {
      "careerName": "Animation",
      "category": "arts_design",
      "categoryName": "Arts & Design",
      "role": "student",
      "description": "Studies motion graphics, visual storytelling, character animation and digital animation techniques.",
      "education": "Students can pursue a degree in Animation, Digital Arts or related field after Intermediate.",
      "skills": ["Animation", "Drawing", "Creativity", "Digital Tools"],
      "scope": "Provides pathways into animation studios, film, advertising, gaming and digital media.",
      "salaryRange": "Depends on portfolio, specialization and experience.",
    },
    {
      "careerName": "Multimedia Design",
      "category": "arts_design",
      "categoryName": "Arts & Design",
      "role": "student",
      "description": "Combines graphic design, digital media, video, audio and interactive content creation.",
      "education": "Students can pursue Multimedia Design, Digital Media or related undergraduate studies.",
      "skills": ["Graphic Design", "Video Editing", "Creativity", "Digital Media"],
      "scope": "Provides pathways into advertising, media companies, digital agencies and content production.",
      "salaryRange": "Depends on portfolio, specialization and experience.",
    },
    {
      "careerName": "Industrial Design",
      "category": "arts_design",
      "categoryName": "Arts & Design",
      "role": "student",
      "description": "Focuses on designing products that combine usability, function and visual appeal.",
      "education": "After Intermediate or equivalent, students can pursue a degree in Industrial Design or related field.",
      "skills": ["Product Design", "Creativity", "CAD", "Problem Solving"],
      "scope": "Provides pathways into product companies, manufacturing, design studios and creative industries.",
      "salaryRange": "Depends on specialization, portfolio and experience.",
    },
    {
      "careerName": "Visual Communication Design",
      "category": "arts_design",
      "categoryName": "Arts & Design",
      "role": "student",
      "description": "Studies how visual elements communicate ideas, information and messages to audiences.",
      "education": "Students can pursue a degree in Visual Communication, Communication Design or related field.",
      "skills": ["Visual Design", "Typography", "Creativity", "Communication"],
      "scope": "Provides pathways into branding, advertising, media, design agencies and digital communication.",
      "salaryRange": "Depends on portfolio, specialization and experience.",
    },
    {
      "careerName": "Photography",
      "category": "arts_design",
      "categoryName": "Arts & Design",
      "role": "student",
      "description": "Studies photographic techniques, visual storytelling, composition and digital image production.",
      "education": "Students can pursue Photography, Fine Arts, Media or related undergraduate studies.",
      "skills": ["Photography", "Composition", "Creativity", "Photo Editing"],
      "scope": "Provides pathways into media, advertising, fashion, events, journalism and freelance photography.",
      "salaryRange": "Depends on portfolio, specialization and assignments.",
    },

    // ==========================================================
    // 11. MEDIA & COMMUNICATION - 10
    // ==========================================================

    {
      "careerName": "Mass Communication",
      "category": "media_communication",
      "categoryName": "Media & Communication",
      "role": "student",
      "description": "Studies communication through television, radio, digital platforms, print and other mass media.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Mass Communication.",
      "skills": ["Communication", "Writing", "Research", "Presentation"],
      "scope": "Provides pathways into media organizations, broadcasting, digital media, advertising and public communication.",
      "salaryRange": "Depends on specialization, organization and experience.",
    },
    {
      "careerName": "Journalism",
      "category": "media_communication",
      "categoryName": "Media & Communication",
      "role": "student",
      "description": "Focuses on researching, verifying and communicating news and information to audiences.",
      "education": "After Intermediate or equivalent, students can pursue a degree in Journalism, Mass Communication or related field.",
      "skills": ["Writing", "Research", "Communication", "Critical Thinking"],
      "scope": "Provides pathways into newspapers, television, digital news, magazines and media organizations.",
      "salaryRange": "Depends on organization, specialization and experience.",
    },
    {
      "careerName": "Public Relations",
      "category": "media_communication",
      "categoryName": "Media & Communication",
      "role": "student",
      "description": "Studies how organizations build relationships and communicate with the public and stakeholders.",
      "education": "Students can pursue Media, Communication, Public Relations or related undergraduate studies.",
      "skills": ["Communication", "Writing", "Public Relations", "Presentation"],
      "scope": "Provides pathways into corporations, PR agencies, NGOs, government and media organizations.",
      "salaryRange": "Depends on organization, specialization and experience.",
    },
    {
      "careerName": "Digital Media",
      "category": "media_communication",
      "categoryName": "Media & Communication",
      "role": "student",
      "description": "Focuses on creating and managing content for digital platforms and online audiences.",
      "education": "After Intermediate or equivalent, students can pursue Digital Media, Media Studies or related degree programs.",
      "skills": ["Content Creation", "Social Media", "Video Editing", "Communication"],
      "scope": "Provides pathways into digital agencies, media companies, brands, social platforms and content production.",
      "salaryRange": "Depends on portfolio, specialization and experience.",
    },
    {
      "careerName": "Film & Television",
      "category": "media_communication",
      "categoryName": "Media & Communication",
      "role": "student",
      "description": "Studies film and television production, storytelling, directing and media production.",
      "education": "Students can pursue Film & Television, Media Studies or related undergraduate programs.",
      "skills": ["Storytelling", "Video Production", "Creativity", "Communication"],
      "scope": "Provides pathways into film studios, television channels, production houses and digital entertainment.",
      "salaryRange": "Depends on role, portfolio, production and experience.",
    },
    {
      "careerName": "Advertising",
      "category": "media_communication",
      "categoryName": "Media & Communication",
      "role": "student",
      "description": "Studies creative communication used to promote products, services and organizations.",
      "education": "Students can pursue Advertising, Media, Marketing or Communication related undergraduate studies.",
      "skills": ["Creativity", "Marketing", "Communication", "Content Creation"],
      "scope": "Provides pathways into advertising agencies, brands, digital marketing and creative industries.",
      "salaryRange": "Depends on specialization, agency and experience.",
    },
    {
      "careerName": "Broadcasting",
      "category": "media_communication",
      "categoryName": "Media & Communication",
      "role": "student",
      "description": "Studies production and distribution of audio and video content through broadcast media.",
      "education": "Students can pursue Media, Broadcasting, Mass Communication or related undergraduate studies.",
      "skills": ["Communication", "Presentation", "Production", "Technical Skills"],
      "scope": "Provides pathways into television, radio, production houses and digital broadcasting.",
      "salaryRange": "Depends on organization, role and experience.",
    },
    {
      "careerName": "Content Creation",
      "category": "media_communication",
      "categoryName": "Media & Communication",
      "role": "student",
      "description": "Focuses on creating written, visual and video content for digital audiences and organizations.",
      "education": "Students can pursue Media, Communication, Marketing or related studies while building practical content skills.",
      "skills": ["Writing", "Video Editing", "Creativity", "Social Media"],
      "scope": "Provides pathways into digital media, brands, agencies, online platforms and freelance content work.",
      "salaryRange": "Depends on portfolio, platform, specialization and experience.",
    },
    {
      "careerName": "Public Speaking & Communication",
      "category": "media_communication",
      "categoryName": "Media & Communication",
      "role": "student",
      "description": "Develops professional communication, presentation and public speaking abilities.",
      "education": "Students can pursue Communication, Media, English or related undergraduate studies.",
      "skills": ["Public Speaking", "Communication", "Presentation", "Writing"],
      "scope": "Provides pathways into media, training, corporate communication, education and public relations.",
      "salaryRange": "Depends on specialization, organization and experience.",
    },
    {
      "careerName": "Media Studies",
      "category": "media_communication",
      "categoryName": "Media & Communication",
      "role": "student",
      "description": "Provides broad academic study of media, communication, digital platforms and media culture.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Media Studies.",
      "skills": ["Communication", "Research", "Writing", "Media Analysis"],
      "scope": "Provides pathways into journalism, digital media, public relations, advertising and media research.",
      "salaryRange": "Depends on specialization, organization and experience.",
    },

    // ==========================================================
    // 12. AGRICULTURE & ENVIRONMENTAL SCIENCES - 10
    // ==========================================================

    {
      "careerName": "Agriculture",
      "category": "agriculture_environmental",
      "categoryName": "Agriculture & Environmental Sciences",
      "role": "student",
      "description": "Studies crop production, soil, agricultural systems and modern farming practices.",
      "education": "After Intermediate or equivalent with relevant subjects, students can pursue a BS degree in Agriculture.",
      "skills": ["Biology", "Agriculture", "Research", "Problem Solving"],
      "scope": "Provides pathways into farming, agricultural organizations, research, agribusiness and government programs.",
      "salaryRange": "Depends on specialization, organization and agricultural business performance.",
    },
    {
      "careerName": "Agronomy",
      "category": "agriculture_environmental",
      "categoryName": "Agriculture & Environmental Sciences",
      "role": "student",
      "description": "Focuses on crop production, soil management and efficient agricultural practices.",
      "education": "Students can pursue a BS degree in Agriculture and specialize in Agronomy.",
      "skills": ["Crop Science", "Soil Science", "Biology", "Research"],
      "scope": "Provides pathways into agriculture research, farming organizations, agribusiness and crop management.",
      "salaryRange": "Depends on specialization, organization and experience.",
    },
    {
      "careerName": "Horticulture",
      "category": "agriculture_environmental",
      "categoryName": "Agriculture & Environmental Sciences",
      "role": "student",
      "description": "Studies the cultivation and management of fruits, vegetables, flowers and ornamental plants.",
      "education": "Students can pursue a BS degree in Agriculture or Horticulture after Intermediate.",
      "skills": ["Plant Science", "Biology", "Agriculture", "Research"],
      "scope": "Provides pathways into farming, nurseries, landscaping, food production and horticultural research.",
      "salaryRange": "Depends on specialization, organization and business performance.",
    },
    {
      "careerName": "Agricultural Economics",
      "category": "agriculture_environmental",
      "categoryName": "Agriculture & Environmental Sciences",
      "role": "student",
      "description": "Combines agriculture and economics to study agricultural markets, resources and farm management.",
      "education": "Students can pursue Agriculture, Agricultural Economics or related undergraduate studies.",
      "skills": ["Economics", "Agriculture", "Data Analysis", "Planning"],
      "scope": "Provides pathways into agribusiness, agricultural policy, markets, banking and development organizations.",
      "salaryRange": "Depends on specialization, organization and experience.",
    },
    {
      "careerName": "Forestry",
      "category": "agriculture_environmental",
      "categoryName": "Agriculture & Environmental Sciences",
      "role": "student",
      "description": "Studies forests, natural resources, conservation and sustainable forest management.",
      "education": "After Intermediate or equivalent with relevant subjects, students can pursue a BS degree in Forestry.",
      "skills": ["Biology", "Environmental Science", "Field Work", "Conservation"],
      "scope": "Provides pathways into forestry departments, conservation organizations, research and environmental projects.",
      "salaryRange": "Depends on qualification, organization and experience.",
    },
    {
      "careerName": "Environmental Science",
      "category": "agriculture_environmental",
      "categoryName": "Agriculture & Environmental Sciences",
      "role": "student",
      "description": "Studies ecosystems, pollution, natural resources and methods for environmental protection.",
      "education": "After Intermediate or equivalent, students can pursue a BS degree in Environmental Science.",
      "skills": ["Environmental Science", "Biology", "Research", "Data Analysis"],
      "scope": "Provides pathways into environmental consulting, research, conservation and government environmental programs.",
      "salaryRange": "Depends on specialization, organization and experience.",
    },
    {
      "careerName": "Environmental Management",
      "category": "agriculture_environmental",
      "categoryName": "Agriculture & Environmental Sciences",
      "role": "student",
      "description": "Focuses on managing environmental resources, sustainability programs and environmental impacts.",
      "education": "Students can pursue Environmental Science, Environmental Management or related undergraduate studies.",
      "skills": ["Environmental Management", "Research", "Planning", "Sustainability"],
      "scope": "Provides pathways into environmental organizations, industries, consulting firms and sustainability programs.",
      "salaryRange": "Depends on organization, specialization and experience.",
    },
    {
      "careerName": "Wildlife Management",
      "category": "agriculture_environmental",
      "categoryName": "Agriculture & Environmental Sciences",
      "role": "student",
      "description": "Studies wildlife, ecosystems, biodiversity and conservation practices.",
      "education": "Students can pursue Biology, Wildlife Management, Environmental Science or related undergraduate studies.",
      "skills": ["Biology", "Conservation", "Field Work", "Research"],
      "scope": "Provides pathways into wildlife departments, conservation organizations, national parks and research institutions.",
      "salaryRange": "Depends on organization, qualification and experience.",
    },
    {
      "careerName": "Food & Agriculture Technology",
      "category": "agriculture_environmental",
      "categoryName": "Agriculture & Environmental Sciences",
      "role": "student",
      "description": "Combines agricultural science and technology to improve food production, processing and agricultural systems.",
      "education": "Students can pursue Agriculture, Food Science, Agricultural Engineering or related undergraduate studies.",
      "skills": ["Agriculture", "Technology", "Food Science", "Problem Solving"],
      "scope": "Provides pathways into agribusiness, food industries, agricultural technology and research organizations.",
      "salaryRange": "Depends on specialization, industry and experience.",
    },
    {
      "careerName": "Climate & Sustainability",
      "category": "agriculture_environmental",
      "categoryName": "Agriculture & Environmental Sciences",
      "role": "student",
      "description": "Studies climate-related challenges, sustainability, resource management and environmental solutions.",
      "education": "Students can pursue Environmental Science, Climate Science, Sustainability or related undergraduate studies.",
      "skills": ["Environmental Science", "Research", "Data Analysis", "Sustainability"],
      "scope": "Provides pathways into sustainability programs, environmental organizations, research, NGOs and climate-related projects.",
      "salaryRange": "Depends on specialization, organization and experience.",
    },
  ];

  // ============================================================
  // ADD STUDENT CAREERS TO careerBank
  // ============================================================

  print("Adding ${careers.length} student careers...");

  for (final career in careers) {
    await firestore.collection("careerBank").add(career);
  }

  print("");
  print("======================================");
  print("SUCCESS");
  print("${careers.length} student careers added.");
  print("Collection: careerBank");
  print("Role: student");
  print("======================================");
}
